// Code generated by Slice Machine. DO NOT EDIT.

import Hero from './Hero';
import HomeSliding from './HomeSliding';
import Image from './Image';
import ImageCards from './ImageCards';
import Quote from './Quote';
import Text from './Text';
import TextWithImage from './TextWithImage';

export {
	Hero,
	HomeSliding,
	Image,
	ImageCards,
	Quote,
	Text,
	TextWithImage,
};

export const components = {
	hero: Hero,
	home_sliding: HomeSliding,
	image: Image,
	image_cards: ImageCards,
	quote: Quote,
	text: Text,
	text_with_image: TextWithImage,
};
